services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DOCKER_DATABASE}'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=${DOCKER_ROOT}'
      - 'MYSQL_USER=${DOCKER_USERNAME}'
    ports:
      - '3306'
